name: Java CI with Maven

on: [push, pull_request]
env:
  SONATYPE_LIFECYCLE_APPLICATION_ID: $(echo "${{ github.repository }}" | cut -d '/' -f2)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Benchmark java
      uses: actions/checkout@master
      with:
        repository: OWASP-Benchmark/BenchmarkJava
        path: master
         

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Create WAR
      run: mvn clean package

    - name: Sonatype Lifecycle Policy Evaluation
      uses: sonatype-nexus-community/iq-github-action@v2
      with:
        serverUrl: ${{ secrets.SONATYPE_LIFECYCLE_URL }}
        username: ${{ secrets.SONATYPE_LIFECYCLE_USERNAME }}
        password: ${{ secrets.SONATYPE_LIFECYCLE_PASSWORD }}
        applicationId: ${{ env.SONATYPE_LIFECYCLE_APPLICATION_ID }}
        stage: Build
        target: ./target/
  